### ISSUE TITLE
Uncaught SyntaxError: Identifier 'Pie' has already been declared

### ISSUE THREAD

**Issue by chris-goodchild** [jarib/har#4]
**OS**: OSX Version 10.11.5
**Browser**: Chrome Version 51.0.2704.103 (64-bit)

**Repro Steps**:
1. `gem install har`
2. `har <my-har-file>.har`
3. Open `http://localhost:9292/viewer/index.html?path=<my-har-file>.har`

**Expected**
To see HAR data rendered 

**Actual**
- Blank page
- Console output of `Uncaught SyntaxError: Identifier 'Pie' has already been declared`

**Comment by jarib** [comment]
This should be fixed in the new 0.1.1 release.
